### ISSUE TITLE
Recompile for SSMS 18.x

### ISSUE THREAD

**Issue by ChandraSaiKarthik** [brink-daniel/ssms-object-explorer-menu#1]
Hey, i did follow the steps to recompile the package and copied the folder to "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Extensions".
But it didn't work. (I know it was not officially supported).
If it could support, it would be nice to have addin.

Further, I am using SSMSboost addin (v 3.12) which supports only SSMS v18.x.
Sadly, the development of SSMSboost has been stopped.
So, i have to stick with SSMS v18.x for some more time.

**Comment by brink-daniel** [comment]
Hi,

You need to replace the lib/SqlPackageBase.dll and lib/SqlWorkbench.Interfaces.dll in the source code with your local SSMS 18.x version of the same files before you compile the project. 

If you still cannot get it working, let me know, I'll create an 18x branch. There might be a few other tweaks to the code required. 

Cheers
Daniel

**Comment by brink-daniel** [comment]
Confirmed. You only need to replace the two dll files and after that the code works perfectly for SSMS v18.12.1.

See branch here with the correct dll files: 
[https://github.com/brink-daniel/ssms-object-explorer-menu/tree/SSMS_v18.12.1](https://github.com/brink-daniel/ssms-object-explorer-menu/tree/SSMS_v18.12.1)

**Comment by ChandraSaiKarthik** [comment]
Thanks @brink-daniel for your quick help.
I use multiple SSMS Addins as below:
- Redgate SQL prompt, SQL Search
- SSMSboost
- SSMStoolspack
- supratimas
- plan explorer

I am not sure which addin is still causing the issue with this addin.
I got a similar issue with **StatisticsReporterSSMSExtension** which i'm still not able to find the RC
